<?php

namespace App\Services\Reports;

final class SimplePdfReportRenderer
{
    public function __construct(private readonly ReportDocumentContent $content) {}

    public function render(array $report): string
    {
        $lines = [];
        foreach ($this->content->blocks($report) as $block) {
            foreach ($this->wrap((string) $block['text'], $block['style'] === 'heading' ? 70 : 92) as $text) {
                $lines[] = ['text' => $text, 'heading' => $block['style'] === 'heading'];
            }
        }

        $pages = array_chunk($lines, 52);
        if ($pages === []) {
            $pages = [[]];
        }

        $objects = [
            1 => '<< /Type /Catalog /Pages 2 0 R >>',
            3 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
            4 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
        ];
        $pageReferences = [];

        foreach ($pages as $index => $pageLines) {
            $pageObject = 5 + ($index * 2);
            $contentObject = $pageObject + 1;
            $pageReferences[] = "{$pageObject} 0 R";
            $stream = $this->pageStream($pageLines, $index + 1, count($pages), $report['report_id']);
            $objects[$pageObject] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents {$contentObject} 0 R >>";
            $objects[$contentObject] = '<< /Length '.strlen($stream)." >>\nstream\n{$stream}\nendstream";
        }

        $objects[2] = '<< /Type /Pages /Count '.count($pages).' /Kids ['.implode(' ', $pageReferences).'] >>';
        ksort($objects);

        $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
        $offsets = [0 => 0];
        foreach ($objects as $number => $object) {
            $offsets[$number] = strlen($pdf);
            $pdf .= "{$number} 0 obj\n{$object}\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $pdf .= 'xref'."\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";
        for ($number = 1; $number <= count($objects); $number++) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$number]);
        }
        $pdf .= 'trailer'."\n<< /Size ".(count($objects) + 1).' /Root 1 0 R >>'."\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF\n";

        return $pdf;
    }

    private function pageStream(array $lines, int $page, int $totalPages, string $reportId): string
    {
        $commands = ['0.08 0.10 0.14 rg'];
        $y = 800;
        foreach ($lines as $line) {
            $font = $line['heading'] ? 'F2' : 'F1';
            $size = $line['heading'] ? 12 : 9;
            if ($line['heading']) {
                $y -= 5;
            }
            $commands[] = "BT /{$font} {$size} Tf 1 0 0 1 42 {$y} Tm (".$this->escape($line['text']).') Tj ET';
            $y -= $line['heading'] ? 17 : 13;
        }
        $footer = $this->escape("{$reportId} | Page {$page} of {$totalPages} | Generated by HorizonBias");
        $commands[] = "0.35 0.38 0.43 rg BT /F1 8 Tf 1 0 0 1 42 24 Tm ({$footer}) Tj ET";

        return implode("\n", $commands);
    }

    private function wrap(string $text, int $width): array
    {
        if ($text === '') {
            return [''];
        }

        $words = preg_split('/\s+/u', trim($text)) ?: [];
        $lines = [];
        $current = '';
        foreach ($words as $word) {
            if (mb_strwidth($word) > $width) {
                if ($current !== '') {
                    $lines[] = $current;
                    $current = '';
                }
                foreach (mb_str_split($word, $width) as $part) {
                    $lines[] = $part;
                }

                continue;
            }
            $candidate = $current === '' ? $word : $current.' '.$word;
            if (mb_strwidth($candidate) > $width) {
                $lines[] = $current;
                $current = $word;
            } else {
                $current = $candidate;
            }
        }
        if ($current !== '') {
            $lines[] = $current;
        }

        return $lines ?: [''];
    }

    private function escape(string $text): string
    {
        $encoded = iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $text);
        $encoded = $encoded === false ? $text : $encoded;
        $encoded = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', '', $encoded) ?? '';

        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $encoded);
    }
}
